[package]
name = "ziggurat-core-metrics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
histogram = "0.6.9"
metrics = "0.20.1"
metrics-util = "0.14.0"
tabled = "0.10"